# Generated by Django 4.1 on 2022-09-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação:')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de modificação:')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome do projeto:')),
                ('foto', models.ImageField(upload_to='Tecnologias', verbose_name='Imagem do projeto:')),
                ('descricao', models.TextField(max_length=700, verbose_name='Descrição:')),
                ('link', models.CharField(max_length=200, verbose_name='Link:')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projétos',
            },
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação:')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de modificação:')),
                ('nome', models.CharField(max_length=15, verbose_name='técnologia:')),
                ('descricao', models.TextField(max_length=250, verbose_name='Descrição:')),
                ('nivel', models.CharField(choices=[('Até 1 ano', 'Iniciante'), ('De 1 á 2 anos', 'Intermediário'), ('Mais de 2 anos', 'Avançado')], max_length=15, verbose_name='Nivel da linguagem:')),
                ('imagem', models.ImageField(upload_to='Tecnologias', verbose_name='Imagem da técnologia:')),
            ],
            options={
                'verbose_name': 'Técnologia',
                'verbose_name_plural': 'Técnologias',
            },
        ),
    ]
