# Generated by Django 4.1 on 2022-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação:')),
                ('modificado', models.DateField(auto_now=True, verbose_name='data de modificação:')),
                ('descricao', models.TextField(max_length=500, verbose_name='Texto:')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
