# Generated by Django 4.1 on 2022-09-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologias',
            name='link',
            field=models.CharField(default=22, max_length=200, verbose_name='Link:'),
            preserve_default=False,
        ),
    ]
