# Generated by Django 4.1 on 2022-09-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tecnologias_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologias',
            name='nivel',
            field=models.CharField(choices=[('Iniciante', 'Até 1 ano'), ('Intermediário', 'De 1 á 2 anos'), ('Avançado', 'Mais de 2 anos')], max_length=15, verbose_name='Tempo de estudo:'),
        ),
    ]
