# Generated by Django 4.1 on 2022-09-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tecnologias_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologias',
            name='descricao',
            field=models.TextField(max_length=400, verbose_name='Descrição:'),
        ),
    ]
